# Configuration parameters for CargoNetSim
simulation:
  time_step: 15
  time_value_of_money: 45
  shortest_paths: 3

fuel_energy:
  HFO: 11.1
  diesel_1: 10.7
  diesel_2: 10.0

fuel_carbon_content:
  HFO: 3.15
  diesel_1: 2.68
  diesel_2: 2.68

fuel_prices:
  HFO: 580.0
  diesel_1: 1.35
  diesel_2: 1.35

carbon_taxes:
  rate: 65
  ship_multiplier: 1.2
  truck_multiplier: 1.1
  train_multiplier: 1.1

transport_modes:
  ship:
    average_speed: 20
    average_fuel_consumption: 50
    average_container_number: 5000
    risk_factor: 0.025
    fuel_type: HFO
  train:
    average_speed: 40
    use_network: true
    average_fuel_consumption: 20
    average_container_number: 400
    risk_factor: 0.006
    fuel_type: diesel_1
  truck:
    average_speed: 70
    use_network: false
    average_fuel_consumption: 15
    average_container_number: 1
    risk_factor: 0.012
    fuel_type: diesel_2
